#!/bin/sh

#########################
#                       #
#     Initializing      #
#                       #
#########################

##
# You should add all tools as composer dependencies or change this path
# 
# composer require phpmd/phpmd
# composer require squizlabs/php_codesniffer
##

PHPCS_BIN=./vendor/bin/phpcs
PHPCBF_BIN=./vendor/bin/phpcbf
STANDARD_FILE=--standard=./phpcs.xml
THEME_FOLDER=./

# Check for PHPCS / PHPCBF
if [ ! -x $PHPCS_BIN ]; then
    echo "[PRE-COMMIT] PHP CodeSniffer is not installed locally."
    echo "[PRE-COMMIT] Please run 'composer install' or check the path: $PHPCS_BIN"
    exit 1
fi

if [ ! -x $PHPCBF_BIN ]; then
    echo "[PRE-COMMIT] PHP Code Beautifier and Fixer is not installed locally."
    echo "[PRE-COMMIT] Please run 'composer install' or check the path: $PHPCBF_BIN"
    exit 1
fi

#########################
#                       #
#       Starting        #
#                       #
#########################

# All files in staging area (no deletions)

PROJECT=$(git rev-parse --show-toplevel)
FILES=$(git diff --name-only --diff-filter=ACMR HEAD $THEME_FOLDER | grep \\.php )

echo $FILES

if [ "$FILES" != "" ]
then
    # Coding Standards

    echo "[PRE-COMMIT] Checking PHPCS..."

    # You can change your PHPCS command here
    $PHPCS_BIN $STANDARD_FILE -ps $FILES

    if [ $? != 0 ]
    then
        echo "[PRE-COMMIT] Coding standards errors have been detected."
        echo "[PRE-COMMIT] Running PHP Code Beautifier"

        # You can change your PHPCBF command here
        $PHPCBF_BIN  $STANDARD_FILE -ps $FILES

        echo "[PRE-COMMIT] Checking PHPCS again..."

        # You can change your PHPCS command here
        $PHPCS_BIN  $STANDARD_FILE -ps $FILES

        echo "[PRE-COMMIT] All errors are that can be fixed automatically - fixed successfully."

        git add $FILES
    else
        echo "[PRE-COMMIT] No errors found."
    fi

fi

exit $?